/*
 * IONOS DBaaS MongoDB REST API
 * With IONOS Cloud Database as a Service, you have the ability to quickly set up and manage a MongoDB database. You can also delete clusters, manage backups and users via the API.   MongoDB is an open source, cross-platform, document-oriented database program. Classified as a NoSQL database program, it uses JSON-like documents with optional schemas.  The MongoDB API allows you to create additional database clusters or modify existing ones. Both tools, the Data Center Designer (DCD) and the API use the same concepts consistently and are well suited for smooth and intuitive use. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.dbaasmongo.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.dbaasmongo.model.Connection;
import com.ionoscloud.dbaasmongo.model.MaintenanceWindow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Properties of a database cluster.
 */
@ApiModel(description = "Properties of a database cluster.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-12T08:52:41.764Z[Etc/UTC]")

public class ClusterProperties {
  
  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;


  public static final String SERIALIZED_NAME_MONGO_D_B_VERSION = "mongoDBVersion";
  @SerializedName(SERIALIZED_NAME_MONGO_D_B_VERSION)
  private String mongoDBVersion;


  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;


  public static final String SERIALIZED_NAME_INSTANCES = "instances";
  @SerializedName(SERIALIZED_NAME_INSTANCES)
  private Integer instances;


  public static final String SERIALIZED_NAME_CONNECTIONS = "connections";
  @SerializedName(SERIALIZED_NAME_CONNECTIONS)
  private List<Connection> connections = null;


  public static final String SERIALIZED_NAME_MAINTENANCE_WINDOW = "maintenanceWindow";
  @SerializedName(SERIALIZED_NAME_MAINTENANCE_WINDOW)
  private MaintenanceWindow maintenanceWindow;


  public static final String SERIALIZED_NAME_TEMPLATE_I_D = "templateID";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_I_D)
  private String templateID;


  public static final String SERIALIZED_NAME_CONNECTION_STRING = "connectionString";
  @SerializedName(SERIALIZED_NAME_CONNECTION_STRING)
  private String connectionString;

  

  public ClusterProperties displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * The name of your cluster.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "MongoDB cluster", value = "The name of your cluster.")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }



  public ClusterProperties mongoDBVersion(String mongoDBVersion) {
    
    this.mongoDBVersion = mongoDBVersion;
    return this;
  }

   /**
   * The MongoDB version of your cluster.
   * @return mongoDBVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "The MongoDB version of your cluster.")

  public String getMongoDBVersion() {
    return mongoDBVersion;
  }


  public void setMongoDBVersion(String mongoDBVersion) {
    this.mongoDBVersion = mongoDBVersion;
  }



  public ClusterProperties location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * The physical location where the cluster will be created. This is the location where all your instances will be located. This property is immutable. 
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "de/txl", value = "The physical location where the cluster will be created. This is the location where all your instances will be located. This property is immutable. ")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }



  public ClusterProperties instances(Integer instances) {
    
    this.instances = instances;
    return this;
  }

   /**
   * The total number of instances in the cluster (one primary and n-1 secondaries). 
   * @return instances
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3", value = "The total number of instances in the cluster (one primary and n-1 secondaries). ")

  public Integer getInstances() {
    return instances;
  }


  public void setInstances(Integer instances) {
    this.instances = instances;
  }



  public ClusterProperties connections(List<Connection> connections) {
    
    this.connections = connections;
    return this;
  }

  public ClusterProperties addConnectionsItem(Connection connectionsItem) {
    if (this.connections == null) {
      this.connections = new ArrayList<Connection>();
    }
    this.connections.add(connectionsItem);
    return this;
  }

   /**
   * Get connections
   * @return connections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Connection> getConnections() {
    return connections;
  }


  public void setConnections(List<Connection> connections) {
    this.connections = connections;
  }



  public ClusterProperties maintenanceWindow(MaintenanceWindow maintenanceWindow) {
    
    this.maintenanceWindow = maintenanceWindow;
    return this;
  }

   /**
   * Get maintenanceWindow
   * @return maintenanceWindow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MaintenanceWindow getMaintenanceWindow() {
    return maintenanceWindow;
  }


  public void setMaintenanceWindow(MaintenanceWindow maintenanceWindow) {
    this.maintenanceWindow = maintenanceWindow;
  }



  public ClusterProperties templateID(String templateID) {
    
    this.templateID = templateID;
    return this;
  }

   /**
   * The unique ID of the template, which specifies the number of cores, storage size, and memory. You cannot downgrade to a smaller template or minor edition (e.g. from business to playground). To get a list of all templates to confirm the changes use the /templates endpoint. 
   * @return templateID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "498ae72f-411f-11eb-9d07-046c59cc737e", value = "The unique ID of the template, which specifies the number of cores, storage size, and memory. You cannot downgrade to a smaller template or minor edition (e.g. from business to playground). To get a list of all templates to confirm the changes use the /templates endpoint. ")

  public String getTemplateID() {
    return templateID;
  }


  public void setTemplateID(String templateID) {
    this.templateID = templateID;
  }



  public ClusterProperties connectionString(String connectionString) {
    
    this.connectionString = connectionString;
    return this;
  }

   /**
   * The connection string for your cluster.
   * @return connectionString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "mongo+srv://m-498ae72f-411f-11eb-9d07-046c59cc737e.mongodb.de-txl.ionos.com", value = "The connection string for your cluster.")

  public String getConnectionString() {
    return connectionString;
  }


  public void setConnectionString(String connectionString) {
    this.connectionString = connectionString;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterProperties clusterProperties = (ClusterProperties) o;
    return Objects.equals(this.displayName, clusterProperties.displayName) && Objects.equals(this.mongoDBVersion, clusterProperties.mongoDBVersion) && Objects.equals(this.location, clusterProperties.location) && Objects.equals(this.instances, clusterProperties.instances) && Objects.equals(this.connections, clusterProperties.connections) && Objects.equals(this.maintenanceWindow, clusterProperties.maintenanceWindow) && Objects.equals(this.templateID, clusterProperties.templateID) && Objects.equals(this.connectionString, clusterProperties.connectionString);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterProperties {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");

    sb.append("    mongoDBVersion: ").append(toIndentedString(mongoDBVersion)).append("\n");

    sb.append("    location: ").append(toIndentedString(location)).append("\n");

    sb.append("    instances: ").append(toIndentedString(instances)).append("\n");

    sb.append("    connections: ").append(toIndentedString(connections)).append("\n");

    sb.append("    maintenanceWindow: ").append(toIndentedString(maintenanceWindow)).append("\n");

    sb.append("    templateID: ").append(toIndentedString(templateID)).append("\n");

    sb.append("    connectionString: ").append(toIndentedString(connectionString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

